#!/bin/sh
set -e

addgroup --system alfred

# Automatically added by dh_installinit
if [ -x "/etc/init.d/alfred" ] || [ -e "/etc/init/alfred.conf" ]; then
	if [ ! -e "/etc/init/alfred.conf" ]; then
		update-rc.d alfred defaults >/dev/null
	fi
	invoke-rc.d alfred start || exit $?
fi
# End automatically added section

